#!/usr/bin/env python3
"""
Audit whether authoritative SVG assets reproduce the tracked PNG outputs.

This is intentionally conservative. It distinguishes between:

- direct SVG authorities that can be rendered and compared automatically
- specialized authorities that still need a sprite-sheet or scripted renderer
- exact matches, close matches, and mismatches

Usage:
    python3 src/scripts/verify_svg_parity.py \
        --input . \
        --output /tmp/sd-svg-parity \
        --recursive \
        --report-markdown docs/PNG_SVG_PARITY_AUDIT.md
"""

from __future__ import annotations

import argparse
import json
import math
import os
import re
import subprocess
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from shutil import which

import vectorize_assets as va


DEFAULT_WORKERS = max(1, min(6, os.cpu_count() or 1))
SPECIALIZED_AUTHORITIES = {
    'src/assets/gtk2/assets.svg': 'GTK2 sprite-sheet authority needs indexed export, not direct full-file rendering',
    'kde/cursors/src/cursors.svg': 'Cursor build pipeline needs hotspot-aware rendering',
    'xfwm4/render-assets.sh': 'XFWM assets are generated by a scripted renderer',
}
PNG_REFERENCE_ALLOWED_ROOTS = {
    'assets',
    'cinnamon',
    'gnome-shell',
    'gtk-2.0',
    'gtk-3.0',
    'gtk-3.20',
    'gtk-4.0',
    'kde',
    'metacity-1',
    'src',
    'unity',
    'xfwm4',
}
PNG_REFERENCE_INCLUDE_SUFFIXES = {
    '.css',
    '.fish',
    '.ini',
    '.js',
    '.py',
    '.qml',
    '.scss',
    '.sh',
    '.theme',
    '.xml',
}
PNG_REFERENCE_EXCLUDE_PARTS = {
    '.git',
    '.pytest_cache',
    '.ruff_cache',
    '__pycache__',
    'docs',
    'tests',
}
PNG_REFERENCE_EXCLUDE_PATHS = {
    'src/scripts/materialize_runtime_asset_svgs.py',
    'src/scripts/vectorize_assets.py',
    'src/scripts/verify_svg_parity.py',
}
PNG_REFERENCE_ALLOWLIST_NAMES = {
    'Makefile',
    'index.theme',
}
THEME_RUNTIME_SUFFIXES = {
    '.css',
    '.qml',
    '.scss',
    '.svg',
    '.theme',
    '.xml',
}
PNG_EXTENSION_ASSIGNMENT_RE = re.compile(r"""(?x)
    (?:
        ^\s*[A-Za-z_][A-Za-z0-9_]*\s*=\s*['"]\.png['"]\s*$
      | ^\s*set\s+-l\s+[A-Za-z_][A-Za-z0-9_]*\s+['"]\.png['"]\s*$
    )
""")
PNG_SUFFIX_PREDICATE_RE = re.compile(r"""(?x)
    (?:
        endswith\(\s*['"]\.png['"]\s*\)
      | with_suffix\(\s*['"]\.[A-Za-z0-9_-]*png['"]\s*\)
    )
""")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description='Audit SVG-to-PNG render parity')
    parser.add_argument('--input', type=Path, default=Path('.'), help='Repo root / input directory')
    parser.add_argument('--output', type=Path, required=True, help='Temporary render output directory')
    parser.add_argument('--recursive', action='store_true', help='Recursively discover PNG files')
    parser.add_argument(
        '--include-existing-svg',
        action='store_true',
        help='Treat existing SVG-backed PNGs as vectorization candidates when building the manifest',
    )
    parser.add_argument('--workers', type=int, default=DEFAULT_WORKERS, help='Comparison worker count')
    parser.add_argument(
        '--renderer',
        choices=('auto', 'rsvg', 'inkscape'),
        default='auto',
        help='SVG renderer to use for parity checks',
    )
    parser.add_argument(
        '--close-rmse-threshold',
        type=float,
        default=0.002,
        help='Normalized RMSE threshold for a close-but-not-exact match',
    )
    parser.add_argument(
        '--close-diff-ratio-threshold',
        type=float,
        default=0.01,
        help='Differing-pixel ratio threshold for a close-but-not-exact match',
    )
    parser.add_argument(
        '--manifest-json',
        type=Path,
        help='Optional JSON output of the classified PNG manifest used for this audit',
    )
    parser.add_argument(
        '--report-json',
        type=Path,
        help='Optional JSON output of per-file parity results',
    )
    parser.add_argument(
        '--report-markdown',
        type=Path,
        help='Optional Markdown output summarizing the parity audit',
    )
    return parser.parse_args()


def choose_renderer(requested: str) -> str:
    if requested == 'rsvg':
        if not which('rsvg-convert'):
            raise RuntimeError('Requested rsvg renderer, but rsvg-convert is not installed')
        return 'rsvg'
    if requested == 'inkscape':
        if not which('inkscape'):
            raise RuntimeError('Requested inkscape renderer, but inkscape is not installed')
        return 'inkscape'

    if which('rsvg-convert'):
        return 'rsvg'
    if which('inkscape'):
        return 'inkscape'
    raise RuntimeError('No supported SVG renderer found; install rsvg-convert or Inkscape')


def parse_ae_metric(raw: str) -> float:
    raw = raw.strip()
    if not raw:
        raise ValueError('Empty AE metric output')
    return float(raw.split()[0])


def parse_rmse_metric(raw: str) -> tuple[float, float]:
    raw = raw.strip()
    match = re.search(r'([0-9.eE+-]+)\s*\(([0-9.eE+-]+)\)', raw)
    if match:
        return float(match.group(1)), float(match.group(2))
    value = float(raw.split()[0])
    return value, value


def image_dimensions(path: Path) -> tuple[int, int]:
    result = subprocess.run(
        ['identify', '-format', '%w %h', str(path)],
        check=True,
        capture_output=True,
        text=True,
    )
    width, height = result.stdout.strip().split()
    return int(width), int(height)


def render_svg(svg_path: Path, output_png: Path, width: int, height: int, renderer: str) -> str:
    output_png.parent.mkdir(parents=True, exist_ok=True)
    renderers = [renderer]
    if renderer == 'rsvg' and which('inkscape'):
        renderers.append('inkscape')

    last_error = None
    for candidate in renderers:
        try:
            if candidate == 'rsvg':
                subprocess.run(
                    [
                        'rsvg-convert',
                        '--format', 'png',
                        '--width', str(width),
                        '--height', str(height),
                        '--output', str(output_png),
                        str(svg_path),
                    ],
                    check=True,
                    capture_output=True,
                    text=True,
                )
                return candidate

            subprocess.run(
                [
                    'inkscape',
                    str(svg_path),
                    '--export-type=png',
                    f'--export-filename={output_png}',
                    f'--export-width={width}',
                    f'--export-height={height}',
                ],
                check=True,
                capture_output=True,
                text=True,
            )
            return candidate
        except subprocess.CalledProcessError as exc:
            last_error = exc

    if last_error is not None:
        raise last_error
    raise RuntimeError(f'Failed to render {svg_path}')


def compare_metric(metric: str, expected_png: Path, rendered_png: Path) -> str:
    result = subprocess.run(
        [
            'compare',
            '-metric', metric,
            str(expected_png),
            str(rendered_png),
            'null:',
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode not in (0, 1):
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or f'compare failed with {result.returncode}')
    return (result.stderr or result.stdout).strip()


def classify_authority_mode(relative_png: str, source_authority: str | None) -> tuple[str, str]:
    if not source_authority:
        return 'missing-authority', 'No authoritative SVG recorded'
    if source_authority in SPECIALIZED_AUTHORITIES:
        return 'specialized-renderer', SPECIALIZED_AUTHORITIES[source_authority]
    if not source_authority.endswith('.svg'):
        return 'specialized-renderer', f'Non-SVG authority requires custom handling: {source_authority}'
    return 'direct-svg', f'Direct SVG render parity candidate for {relative_png}'


def is_raster_wrapper_authority(source_authority: str | None) -> bool:
    return bool(source_authority and source_authority.startswith('src/raster_wrappers/'))


def grade_parity(
    differing_pixels: float,
    normalized_rmse: float,
    width: int,
    height: int,
    close_rmse_threshold: float,
    close_diff_ratio_threshold: float,
    source_authority: str | None = None,
) -> tuple[str, float]:
    total_pixels = max(1, width * height)
    differing_ratio = differing_pixels / total_pixels
    if math.isclose(differing_pixels, 0.0) and math.isclose(normalized_rmse, 0.0):
        return 'exact', differing_ratio
    if is_raster_wrapper_authority(source_authority) and normalized_rmse <= close_rmse_threshold:
        return 'close', differing_ratio
    if normalized_rmse <= close_rmse_threshold and differing_ratio <= close_diff_ratio_threshold:
        return 'close', differing_ratio
    return 'mismatch', differing_ratio


def audit_single_entry(
    repo_root: Path,
    render_root: Path,
    entry: dict,
    renderer: str,
    close_rmse_threshold: float,
    close_diff_ratio_threshold: float,
) -> dict:
    relative_png = entry['relative_png']
    source_authority = entry.get('source_authority')
    authority_mode, detail = classify_authority_mode(relative_png, source_authority)

    result = {
        'relative_png': relative_png,
        'semantic_id': entry['semantic_id'],
        'family': entry['family'],
        'style_skin': entry['style_skin'],
        'source_authority': source_authority,
        'authority_mode': authority_mode,
        'detail': detail,
        'renderer_used': None,
        'parity_status': 'not-run',
        'width': None,
        'height': None,
        'differing_pixels': None,
        'differing_ratio': None,
        'rmse': None,
        'normalized_rmse': None,
    }

    if authority_mode != 'direct-svg':
        result['parity_status'] = authority_mode
        return result

    png_path = repo_root / relative_png
    svg_path = repo_root / source_authority
    rendered_png = render_root / Path(relative_png).with_suffix('.rendered.png')

    try:
        width, height = image_dimensions(png_path)
        renderer_used = render_svg(svg_path, rendered_png, width, height, renderer)
        ae = parse_ae_metric(compare_metric('AE', png_path, rendered_png))
        rmse, normalized_rmse = parse_rmse_metric(compare_metric('RMSE', png_path, rendered_png))
        status, differing_ratio = grade_parity(
            ae,
            normalized_rmse,
            width,
            height,
            close_rmse_threshold,
            close_diff_ratio_threshold,
            source_authority=source_authority,
        )
        result.update({
            'parity_status': status,
            'width': width,
            'height': height,
            'renderer_used': renderer_used,
            'differing_pixels': ae,
            'differing_ratio': differing_ratio,
            'rmse': rmse,
            'normalized_rmse': normalized_rmse,
        })
        return result
    except Exception as exc:
        result['parity_status'] = 'error'
        result['detail'] = str(exc)
        return result


def build_parity_summary(results: list[dict]) -> dict:
    by_status = Counter(item['parity_status'] for item in results)
    by_mode = Counter(item['authority_mode'] for item in results)
    by_root = Counter(Path(item['relative_png']).parts[0] for item in results)
    direct_results = [item for item in results if item['authority_mode'] == 'direct-svg']
    direct_by_status = Counter(item['parity_status'] for item in direct_results)
    return {
        'total': len(results),
        'by_status': dict(by_status),
        'by_mode': dict(by_mode),
        'by_root': dict(by_root),
        'direct_total': len(direct_results),
        'direct_by_status': dict(direct_by_status),
    }


def classify_reference_kind(relative_path: Path) -> str:
    if relative_path.name == 'index.theme' or relative_path.suffix.lower() in THEME_RUNTIME_SUFFIXES:
        return 'theme-runtime'
    return 'build-tooling'


def is_actionable_png_reference_line(line: str) -> bool:
    if '.png' not in line:
        return False
    if PNG_EXTENSION_ASSIGNMENT_RE.match(line):
        return False
    if PNG_SUFFIX_PREDICATE_RE.search(line):
        return False
    return True


def collect_runtime_png_references(repo_root: Path) -> list[dict]:
    hits = []
    for path in sorted(repo_root.rglob('*')):
        if not path.is_file():
            continue
        relative_path = path.relative_to(repo_root)
        if any(part in PNG_REFERENCE_EXCLUDE_PARTS for part in relative_path.parts):
            continue
        if relative_path.as_posix() in PNG_REFERENCE_EXCLUDE_PATHS:
            continue
        if relative_path.parts[:2] == ('src', 'icons_backend'):
            continue
        top_level = relative_path.parts[0] if relative_path.parts else ''
        if (
            top_level not in PNG_REFERENCE_ALLOWED_ROOTS
            and relative_path.name not in PNG_REFERENCE_ALLOWLIST_NAMES
        ):
            continue
        if (
            path.suffix.lower() not in PNG_REFERENCE_INCLUDE_SUFFIXES
            and relative_path.name not in PNG_REFERENCE_ALLOWLIST_NAMES
        ):
            continue
        try:
            text = path.read_text(encoding='utf-8')
        except UnicodeDecodeError:
            continue
        for lineno, line in enumerate(text.splitlines(), start=1):
            if not is_actionable_png_reference_line(line):
                continue
            hits.append({
                'path': relative_path.as_posix(),
                'line': lineno,
                'text': line.strip(),
                'reference_kind': classify_reference_kind(relative_path),
            })
    return hits


def render_markdown_report(
    manifest: list[dict],
    results: list[dict],
    summary: dict,
    renderer: str,
    runtime_png_references: list[dict],
) -> str:
    safe_entries = [entry for entry in manifest if entry['batch_priority'] == 'safe-batch-generation']
    mismatches = [item for item in results if item['parity_status'] == 'mismatch']
    close_matches = [item for item in results if item['parity_status'] == 'close']
    exact_matches = [item for item in results if item['parity_status'] == 'exact']
    specialized = [item for item in results if item['parity_status'] == 'specialized-renderer']
    refs_by_kind = Counter(hit['reference_kind'] for hit in runtime_png_references)

    mismatches.sort(
        key=lambda item: (
            -(item['normalized_rmse'] or 0.0),
            -(item['differing_ratio'] or 0.0),
            item['relative_png'],
        )
    )
    close_matches.sort(
        key=lambda item: (
            -(item['normalized_rmse'] or 0.0),
            -(item['differing_ratio'] or 0.0),
            item['relative_png'],
        )
    )

    lines = [
        '# PNG/SVG Parity Audit',
        '',
        '## Summary',
        f"- Safe-batch-generation PNGs discovered: `{len(safe_entries)}`",
        f"- Direct render parity candidates: `{summary['direct_total']}`",
        f"- Exact matches: `{summary['direct_by_status'].get('exact', 0)}`",
        f"- Close matches needing review: `{summary['direct_by_status'].get('close', 0)}`",
        f"- Mismatches: `{summary['direct_by_status'].get('mismatch', 0)}`",
        f"- Specialized renderer cases: `{summary['by_status'].get('specialized-renderer', 0)}`",
        f"- Errors: `{summary['by_status'].get('error', 0)}`",
        f"- Renderer used for direct checks: `{renderer}`",
        f"- Theme/runtime `.png` references still in tree: `{refs_by_kind.get('theme-runtime', 0)}`",
        f"- Build/tooling `.png` references still in tree: `{refs_by_kind.get('build-tooling', 0)}`",
        '',
        '## Decision',
        '- Do not delete PNGs solely because an SVG authority exists.',
        '- Delete or stop tracking a PNG only after both conditions hold: exact or accepted-close render parity, and no remaining runtime path dependency on that `.png` filename.',
        '- The highest-risk remaining authority class is sprite-sheet or scripted generation, where an SVG exists but the exported PNG is not a trivial one-file render.',
        '',
        '## Specialized Renderer Cases',
    ]

    if specialized:
        counts = Counter(item['source_authority'] for item in specialized)
        for authority, count in counts.most_common():
            lines.append(f"- `{authority}`: `{count}` outputs")
    else:
        lines.append('- None')

    lines.extend([
        '',
        '## Largest Mismatches',
    ])
    if mismatches:
        for item in mismatches[:25]:
            lines.append(
                f"- `{item['relative_png']}` <= `{item['source_authority']}` "
                f"(rmse=`{item['normalized_rmse']:.6f}`, diff_ratio=`{item['differing_ratio']:.6f}`)"
            )
    else:
        lines.append('- None')

    lines.extend([
        '',
        '## Close Matches',
    ])
    if close_matches:
        for item in close_matches[:25]:
            lines.append(
                f"- `{item['relative_png']}` <= `{item['source_authority']}` "
                f"(rmse=`{item['normalized_rmse']:.6f}`, diff_ratio=`{item['differing_ratio']:.6f}`)"
            )
    else:
        lines.append('- None')

    lines.extend([
        '',
        '## Exact-Match Coverage By Top-Level Root',
    ])
    exact_by_root = Counter(Path(item['relative_png']).parts[0] for item in exact_matches)
    for root, count in exact_by_root.most_common():
        lines.append(f"- `{root}`: `{count}`")
    if not exact_by_root:
        lines.append('- None')

    lines.extend([
        '',
        '## Theme/Runtime `.png` References Still In Tree',
        '- These are direct blockers for removing PNGs without also updating theme/runtime consumers.',
    ])
    runtime_hits = [hit for hit in runtime_png_references if hit['reference_kind'] == 'theme-runtime']
    if runtime_hits:
        by_file = Counter(hit['path'] for hit in runtime_hits)
        for path, count in by_file.most_common(20):
            lines.append(f"- `{path}`: `{count}` references")
    else:
        lines.append('- None found')

    lines.extend([
        '',
        '## Build/Tooling `.png` References',
        '- These do not by themselves block migration, but they must be updated if PNG generation rules change.',
    ])
    build_hits = [hit for hit in runtime_png_references if hit['reference_kind'] == 'build-tooling']
    if build_hits:
        by_file = Counter(hit['path'] for hit in build_hits)
        for path, count in by_file.most_common(20):
            lines.append(f"- `{path}`: `{count}` references")
        lines.extend([
            '',
            '## Sample `.png` Reference Lines',
        ])
        for hit in runtime_png_references[:20]:
            lines.append(
                f"- `{hit['path']}:{hit['line']}` [{hit['reference_kind']}]: `{hit['text']}`"
            )
        if len(runtime_png_references) > 40:
            lines.append(f"- ... and `{len(runtime_png_references) - 40}` more")
    else:
        lines.append('- None found')

    return '\n'.join(lines) + '\n'


def main() -> int:
    args = parse_args()
    repo_root = args.input.resolve()
    render_root = args.output.resolve()
    render_root.mkdir(parents=True, exist_ok=True)

    renderer = choose_renderer(args.renderer)
    manifest = va.build_asset_manifest(
        repo_root,
        render_root,
        recursive=args.recursive,
        include_existing_svg=args.include_existing_svg,
    )
    safe_entries = [entry for entry in manifest if entry['batch_priority'] == 'safe-batch-generation']

    results = []
    with ThreadPoolExecutor(max_workers=max(1, args.workers)) as executor:
        futures = {
            executor.submit(
                audit_single_entry,
                repo_root,
                render_root,
                entry,
                renderer,
                args.close_rmse_threshold,
                args.close_diff_ratio_threshold,
            ): entry['relative_png']
            for entry in safe_entries
        }
        for future in as_completed(futures):
            results.append(future.result())

    results.sort(key=lambda item: item['relative_png'])
    summary = build_parity_summary(results)
    runtime_png_references = collect_runtime_png_references(repo_root)

    print('=== Synthesis-Dark PNG/SVG Parity Audit ===')
    print(f"Renderer: {renderer}")
    print(f"Safe-batch PNGs: {len(safe_entries)}")
    print(f"Direct candidates: {summary['direct_total']}")
    print(f"Exact matches: {summary['direct_by_status'].get('exact', 0)}")
    print(f"Close matches: {summary['direct_by_status'].get('close', 0)}")
    print(f"Mismatches: {summary['direct_by_status'].get('mismatch', 0)}")
    print(f"Specialized renderer cases: {summary['by_status'].get('specialized-renderer', 0)}")
    print(f"Errors: {summary['by_status'].get('error', 0)}")
    print(f"Runtime .png references found: {len(runtime_png_references)}")

    if args.manifest_json:
        args.manifest_json.parent.mkdir(parents=True, exist_ok=True)
        args.manifest_json.write_text(json.dumps(manifest, indent=2), encoding='utf-8')
        print(f"Wrote manifest: {args.manifest_json}")

    if args.report_json:
        args.report_json.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            'renderer': renderer,
            'summary': summary,
            'results': results,
            'runtime_png_references': runtime_png_references,
        }
        args.report_json.write_text(json.dumps(payload, indent=2), encoding='utf-8')
        print(f"Wrote JSON report: {args.report_json}")

    if args.report_markdown:
        args.report_markdown.parent.mkdir(parents=True, exist_ok=True)
        report = render_markdown_report(
            manifest,
            results,
            summary,
            renderer,
            runtime_png_references,
        )
        args.report_markdown.write_text(report, encoding='utf-8')
        print(f"Wrote Markdown report: {args.report_markdown}")

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
